form_test/urls.py
from django.contrib import admin
from django.urls import path, re_path
from form_test.views import here, add, menu, menu_db, meta, welcome, get_menu, comment, index, login, logout, list_restaurants, register
from django.contrib.auth import views
from django .contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'here/(?P<id>[\s\S]*)', here),
    re_path(r'(\d{1,2})/plus/(\d{1,2})', add),
    path('menu/', menu),
    path('menu_db/', menu_db),
    path('meta/', meta),
    path('welcome/', welcome),
    path('get_menu/', get_menu),
    re_path(r'get_menu/(\d{1,5})', get_menu),
    re_path(r'comment/(?P<id>\d{1,5})', comment), # ?P<關鍵字>要擷取的參數可以從URL中將要擷取的參數以關鍵字的方式取出
                                                # 例如/comment/1會將'1'給id
                                                # \d{1,5}是指1-5個數字

    # 實作內建登入認證
    path('index/', index),
    path('login/', login), # Djaongo 內建的登入登出判定(語法是固定用法)
    path('logout/', logout), # 要把login.html logged_out.html放到registration下

    # Django內建的登入認證
    path('accounts/login/', views.LoginView.as_view(), name='login'), # Djaongo 內建的登入登出判定(語法是固定用法)
    path('accounts/logout/', views.LogoutView.as_view(), name='logout'), # 要把login.html logged_out.html放到registration下
    path('accounts/profile/', index),
    
    path('restaurants_list/', login_required(list_restaurants)), # login_required可以擋掉沒登入的使用者用url直接進去
    path('accounts/register/', register),
]

form_test/models.py
from django.db import models

class Restaurant(models.Model):
    name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=15)
    address = models.CharField(max_length=50, blank=True)


class Food(models.Model):
    name = models.CharField(max_length=20) 
    price=models.DecimalField(max_digits=3,decimal_places=0) # decimal_places小數點位數
    comment = models.CharField(max_length=50, blank=True) # blank允許欄位為空
    is_spicy = models.BooleanField(default=False) 
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)

# 詳細資料庫CRUD操作參考 https://ithelp.ithome.com.tw/articles/10212427

class Comment(models.Model):
    content = models.CharField(max_length=200)
    visitor = models.CharField(max_length=20)
    email = models.EmailField(max_length=20)
    date_time = models.DateTimeField()
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)

    class Meta: # 新增權限 每一個權限都會跟一個資料庫模型綁定
            ordering = ['date_time']
            permissions = (
                ("can_comment", "Can comment"),  # 只有一個權限時，千萬不要忘了逗號！
                # 第一個元素是codename字串(實際運用在代碼中的權限名稱)，第二個元素是name字串(用戶名稱，通常只是拿來顯示，好閱讀的)
            )

zoo/models.py
from django.db import models

class Animal(models.Model):
    name = models.CharField(max_length=256)

    def says(self):
        raise NotImplementedError("I don't know what to do")

    class Meta:
        abstract = True

class Dog(Animal):

    def says(self):
        return "woof"

class Cat(Animal):

    def says(self):
        return "meow"

form_test/forms.py
from django import forms

class CommentForm(forms.Form):
    visitor = forms.CharField(max_length=20)
    email = forms.EmailField(max_length=20, required=False) # required:是否必填
    content = forms.CharField(max_length=200, widget=forms.Textarea())

    def clean_content(self):
        content = self.cleaned_data['content']
        if len(content) < 5:
            raise forms.ValidationError('字數不足')
        return content

form_test/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django import template
from django.template.loader import get_template
from django.shortcuts import render
from form_test.models import Restaurant, Food, Comment
from django.utils import timezone
from form_test.forms import CommentForm
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from urllib.parse import unquote

def here(request,id):
    id = unquote(id)
    return HttpResponse(f'{id} Mom, I am here!')

# def add(request, a, b):
#     s = int(a) + int(b)
#     t = template.Template('<html>sum={{s}}</html>')
#     c = template.Context({'s': s})
#     return HttpResponse(t.render(c))

# 將html自template載入簡化程式碼
# def add(request, a, b):
#     s = int(a) + int(b)
#     with open('templates/main.html', 'r') as reader:
#         t = template.Template(reader.read())
#     c = template.Context({'s': s})
#     return HttpResponse(t.render(c))

# 
def add(request, a, b):
    s = int(a) + int(b)
    t = get_template('main.html')
    c = {'s': s}
    return HttpResponse(t.render(c))

def menu(request):
    food1 = {'name': '番茄炒蛋', 'price': 60, 'comment': '好吃', 'is_spicy': False}
    food2 = {'name': '蒜泥白肉', 'price': 100, 'comment': '人氣推薦', 'is_spicy': True}
    foods = [food1, food2]
    return render(request, 'menu.html', locals())

def menu_db(request):
    path = request.path
    # restaurants = Restaurant.objects.get(id=1)
    restaurants = Restaurant.objects.all()
    return render(request,'menu_db.html', locals())

def meta(request): # request包的資訊
    values = request.META.items()
    html = []
    for k, v in values:
        html.append('<tr><td>{0}</td><td>{1}</td></tr>'.format(k, v))
    return HttpResponse('<table>{0}</table>'.format('\n'.join(html)))

def welcome(request): # get test
    if 'user_name' in request.GET and request.GET['user_name'] != '':
        return HttpResponse('Welcome!~' + request.GET['user_name'])
    else:
        return render(request, 'welcome.html', locals())
    
def get_menu(request,id): # 資料庫連結
    foods = Food.objects.get(id=id)
    return render(request, 'get_menu.html', locals())

def comment(request, id): # 留言頁
    if id:
        r = Restaurant.objects.get(id=id)
    else:
        return HttpResponseRedirect("/get_menu/")
    errors = []
    if request.POST:
        # --------- 內建表單建立方法 ----------# 
        visitor = request.POST['visitor']
        content = request.POST['content']
        email = request.POST['email']
        date_time = timezone.localtime(timezone.now()) # 擷取現在時間
        if any(not request.POST[k] for k in request.POST): # 驗證資料是否合格式及報錯訊息
            errors.append('* 有空白欄位，請不要留空')
        if '@' not in email:
            errors.append('* email格式不正確，請重新輸入')
        if not errors: # 沒問題才進資料庫
            Comment.objects.create(visitor=visitor, email=email, content=content, date_time=date_time, restaurant=r)
            visitor, content, email = ('', '', '')
        
    # --------- 外插表單建立方法 ----------# 
    f = CommentForm(initial={'content': '我沒意見'})
    
    return render(request, 'comments.html', locals())

def login(request): # 登入頁(實作登入認證)
    if request.user.is_authenticated:
        return HttpResponseRedirect('/index/')
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)
    if user is not None and user.is_active:
        auth.login(request, user)
        return HttpResponseRedirect('/index/')
    else:
        return render(request, 'registration/login.html', locals())
    
def logout(request): # 登出頁(實作登出認證)
    auth.logout(request)
    return HttpResponseRedirect('/index/')

def index(request): # 登入後導向頁
    return render(request, 'registration/logged_out.html')

def list_restaurants(request): # 登入後餐廳列表
    restaurants = Restaurant.objects.all()
    return render(request,'menu_db.html', locals())

def register(request): #註冊頁
    if request.method == 'POST':
        form = UserCreationForm(request.POST) # 內建的註冊表單模型UserCreationForm
        if form.is_valid():
            user = form.save()
            return HttpResponseRedirect('/accounts/login/')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', locals())

zoo/views.py
from django.shortcuts import render

# Create your views here.

templates/comments.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title> Comments </title>
    </head>
    <body>
        <h2>{{ r.name }}的評價</h2>
        {% if r.comment_set.all %}
            <p>目前共有{{ r.comment_set.all|length }}條評價</p>
            <table>
                <tr>
                    <th>留言者</th>
                    <th>時間</th>
                    <th>評價</th>
                </tr>
            {% for c in r.comment_set.all %}
                <tr>
                    <td> {{ c.visitor }} </td>
                    <td> {{ c.date_time | date:"F j, Y" }} </td>
                    <td> {{ c.content }} </td>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            <p>無評價</p>
        {% endif %}
        {% for e in errors %}
            <p style="color: red;">{{ e }}</p>
        {% endfor %}
        <br/>

        <!-- 內建表單建立方法 -->
        <!-- action功用其實跟Redirect類似，看提交後會到哪個url -->
        <form action="" method="post"> {% csrf_token %}
            <table>
                <tr>
                    <td> <label for="visitor">留言者:</label> </td>
                    <td> <input id="visitor" type="text" name="visitor" value="{{visitor}}"> </td>
                </tr>
                <tr>
                    <td> <label for="email">電子信箱:</label> </td>
                    <td> <input id="email" type="email" name="email" value="{{email}}"> </td>
                </tr>
                <tr>
                    <td> <label for="content">評價:</label> </td>
                    <td> 
                        <textarea id="content" rows="10" cols="48" name="content" value="{{content}}"></textarea>
                    </td>
                </tr>
            </table>
            <input type="submit" value="給予評價">
        </form>
        <br/><br/>
        
        <!-- 外插表單建立方法 -->
        <form action="" method="post"> {% csrf_token %}
            <table>
                {{ f.as_table }}
            </table>
            <input type="submit" value="給予評價">
        </form>
    </body>
</html>

templates/get_menu.html
<!DOCTYPE html>
<html>
    <head>
        <title> Menu </title>
        <meta charset="UTF-8">
    </head>
    <body>
        <ul>
            <li> 食物的名字是: {{ foods.name }}</li>
            <li> 食物的價格是: {{ foods.price }}</li>
            <li> 食物說明: {{ foods.comment }}</li>
            <li> 食物會辣? {{ foods.is_spicy }}</li>
        </ul>
    </body>
</html>

templates/main.html
<html>
    sum={{s}} change page<br>
</html>

templates/menu.html
<!DOCTYPE html>
<html>
    <head>
        <title> Menu </title>
        <meta charset="UTF-8">
    </head>
    <body>
        <p>本餐廳共有 {{ foods|first|length }} 道菜</p>
        {% for food in foods %}
        <h3>第{{ forloop.counter }}道食物</h3>
        <ul>
            <li> 食物的名字是: {{ food.name }}</li>
            <li> 食物的價格是: {{ food.price }}</li>
            <li> 食物說明: {{ food.comment }}</li>
            <li> 食物會辣? {{ food.is_spicy }}</li>
        </ul>
        {% endfor %}
    </body>
</html>

templates/menu_db.html
<!doctype html>
<html>

<head>
    <title> Menu </title>
    <meta charset='UTF-8'>
    <style>
        table,
        th,
        td {
            border: 1px solid black;
        }
    </style>
</head>

<body>
    <h2>餐廳列表QQQ</h2>
    <form action="/get_menu/" method="get">
        <p>您現在的位置在{{ path }}</p>
        <table>
            <tr>
                <th>選取</th>
                <th>店名</th>
                <th>電話</th>
                <th>地址</th>
                <th>評價</th>
            </tr>
            {% for r in restaurants %}
            <tr>
                <!-- 用get傳id資訊 -->
                <!-- <td> <input type="radio" name="id" value="{{r.id}}"> </td> -->
                <!-- 用a也可以 -->
                <!-- <td> <a href="/get_menu/?id={{r.id}}"> menu </a></td>  -->
                <!-- 直接接在後面變成是URL的arg -->
                <td> <a href="/get_menu/{{r.id}}"> menu </a></td> 

                <td>{{ r.name }}</td>
                <td>{{ r.phone_number }}</td>
                <td>{{ r.address }}</td>
                <td> <a href="/comment/{{r.id}}/"> comment </a> </td>


                <!-- {% if r.food_set.all %}
                <p>本餐廳共有{{ r.food_set.all|length }}道菜</p>
                <table>
                    <tr>
                        <th>菜名</th>
                        <th>價格</th>
                        <th>註解</th>
                        <th>辣不辣</th>
                    </tr>
                {% for food in r.food_set.all %}
                    <tr>
                        <td> {{ food.name }} </td>
                        <td> {{ food.price }} </td>
                        <td> {{ food.comment }} </td>
                        <td> {% if food.is_spicy %} 辣 {% else %} 不辣 {% endif %} </td>
                    </tr>
                {% endfor %}
                </table>
            {% else %}
                <p>本餐廳啥都沒賣</p>
            {% endif %} -->



            </tr>
            {% endfor %}
        </table>
        <input type="submit" value="觀看menu">
    </form>
</body>

</html>

templates/welcome.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title> Welcome </title>
    </head>
    <body>
        <form action="/welcome/" method="get">
        <!-- 點擊後到哪個function進而決定到哪個頁面 -->
            <label for="user_name">您的名字</label>
            <input id="user_name" type="text" name="user_name"> 
            <!-- get表單值是用input name當作變數傳遞 -->
            <input type="submit" value="進入網站">
            <!-- value是顯示在button上的值 -->
        </form>
    </body>
</html>